name = "spicy-lyrics-external-sources"
main = "src/index.ts"
compatibility_date = "2026-07-12"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[cache]
enabled = true

[observability]
enabled = true
head_sampling_rate = 0.1

[observability.logs]
invocation_logs = false
